### PR TITLE
[1929], [1930] and [1931] - A couple of small provider-led snags

### PR DESCRIPTION
**Pull request by darokel**
### Context

- https://trello.com/c/f5rQzGTW/1929-s-replace-review-and-submit-with-final-check
- https://trello.com/c/NjL0oeqK/1930-s-check-h2-margins
- https://trello.com/c/tiZZ3nUj/1931-s-change-page-title-to-record-submitted-on-trn-record-submission-page

### Changes proposed in this pull request

- A couple of snags from the provider-led demo

### Guidance to review

- https://register-pr-980.london.cloudapps.digital/

### CODE REVIEW

**Comment by darokel** [comment]
[[S] Replace Review and Submit with Final Check](https://trello.com/c/f5rQzGTW/1929-s-replace-review-and-submit-with-final-check)

**Comment by darokel** [comment]
[[S] Check H2 margins](https://trello.com/c/NjL0oeqK/1930-s-check-h2-margins)

**Comment by darokel** [comment]
[[S] Change Page title to Record submitted on trn record submission page](https://trello.com/c/tiZZ3nUj/1931-s-change-page-title-to-record-submitted-on-trn-record-submission-page)

**Review by dankmitchell — APPROVED** [review]
Code and review app looks good

**Comment by GeoffJohnson** [comment]
All good! 🏄‍♂️

**Pull request merged**
