### PR TITLE
[6078] Bump ruby to 3.2.2

### PR DESCRIPTION
**Pull request by darokel**
### Context

https://trello.com/c/VZxyXLG0/6078-update-ruby-and-node-to-latest-stable-versions

### Changes proposed in this pull request

- Bumps ruby to 3.2.2 in all the relevant areas

### CODE REVIEW

**Review by carlosmartinez — APPROVED** [review]

**Comment by carlosmartinez** [comment]
`yarn` is a pretty annoying thing to be failing in the build here. should we upgrade node simultaneously?

**Comment by darokel** [comment]
@carlosmartinez yeah tried doing that but then got this rabbit hole. I don't want to wonder too deep so will leave notes:

Our node version is currently blocking this upgrade. ruby:3.2.2-alpine3.17 contains Node 18.x which has a breaking change causing our current webpack version to fail with:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/register-trainee-teachers/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/register-trainee-teachers/node_modules/webpack/lib/NormalModule.js:417:16)
    at /register-trainee-teachers/node_modules/webpack/lib/NormalModule.js:452:10
    at /register-trainee-teachers/node_modules/webpack/lib/NormalModule.js:323:13
    at /register-trainee-teachers/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /register-trainee-teachers/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/register-trainee-teachers/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /register-trainee-teachers/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

This is a cascading problem because the `@rails/webpacker` library is now retired and the last version available is what we currently have (we also have to pin the `webpack-dev-server` to a specific version to match). This is incompatible with the latest version of `webpack` and the `webpack-dev-server` which contains a fix to the initial problem mentioned above ([context](https://sebhastian.com/error-0308010c-digital-envelope-routines-unsupported/))

Ultimately this prevents us from re-building assets.

We're sort of left with two options:

- Get rid of webpacker and replace with esbuiild so we can use the latest node (and also be able to bump ruby)
- Find a higer ruby image which contains a compatible version of node (16.x) (given it's end of life it might be a bit difficult)

Additional context:

- https://github.com/webpack/webpack/issues/11649#issuecomment-779781768
- https://stackoverflow.com/questions/69046801/brand-new-rails-6-1-4-1-fails-with-webpack-error-typeerror-class-constructor

**Comment by darokel** [comment]
@carlosmartinez yeah tried that but still got some issues, I'll leave notes here before I wonder too deep:

Our node version is currently blocking this upgrade. ruby:3.2.2-alpine3.17 contains Node 18.x which has a breaking change causing our current webpack version to fail with:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/register-trainee-teachers/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/register-trainee-teachers/node_modules/webpack/lib/NormalModule.js:417:16)
    at /register-trainee-teachers/node_modules/webpack/lib/NormalModule.js:452:10
    at /register-trainee-teachers/node_modules/webpack/lib/NormalModule.js:323:13
    at /register-trainee-teachers/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /register-trainee-teachers/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/register-trainee-teachers/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /register-trainee-teachers/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

This is a cascading problem because the `@rails/webpacker` library is now retired and the last version available is what we currently have (we also have to pin the `webpack-dev-server` to a specific version to match). This is incompatible with the latest version of `webpack` and the `webpack-dev-server` which contains a fix to the initial problem mentioned above ([context](https://sebhastian.com/error-0308010c-digital-envelope-routines-unsupported/)).

There is a higher version available for `@rails/webpacker` which i think addresses this issue https://www.npmjs.com/package/@rails/webpacker/v/6.0.0-rc.6 but it's a release candidate and there is an upgrade guide which we may have to do https://github.com/rails/webpacker/blob/master/docs/v6_upgrade.md.

A couple of options:

- Try to upgrade to the release candidate to see if it unblocks the ruby upgrade
- Get rid of webpacker and replace with esbuild so we can use the latest node (and also be able to bump ruby)
- Find a higer ruby image which contains a compatible version of node (16.x) (given it's end of life it might be a bit difficult)

Additional context:

- https://github.com/webpack/webpack/issues/11649#issuecomment-779781768
- https://stackoverflow.com/questions/69046801/brand-new-rails-6-1-4-1-fails-with-webpack-error-typeerror-class-constructor

**Comment by carlosmartinez** [comment]
@darokel shall we close this for now?

**Comment by darokel** [comment]
Closing as we're sorting out the elephant in the room first

**Review by carlosmartinez — APPROVED** [review]

**Review by RMcVelia — APPROVED** [review]

**Review by defong — APPROVED** [review]

**Pull request merged**
