### PR TITLE
[429] add sha endpoint

### PR DESCRIPTION
**Pull request by misaka**
### Context

Sometimes it's crucial to know what the latest commit is in the deployed env.

### Changes proposed in this pull request

Add a `/sha` endpoint which returns the SHA of the latest commit that's deployed out.

### Guidance to review

~~The SHA returned in `/sha` should match the latest commit. EZ!~~

Nope, not so EZ. This is failing in the preview app, probably because Heroku doesn't use the Docker image to deploy but relies on taking the version straight from Git. 🤦

### CODE REVIEW

**Comment by misaka** [comment]
[Add `/sha` endpoint to register](https://trello.com/c/KFBaPemD/429-add-sha-endpoint-to-register)

**Comment by defong** [comment]
https://dfe-twd-rttd-pr-155.herokuapp.com/sha

:thinking:

**Comment by misaka** [comment]
> [dfe-twd-rttd-pr-155.herokuapp.com/sha](https://dfe-twd-rttd-pr-155.herokuapp.com/sha)
> 
> 🤔

Ya, I know. I'm trying to sort it out ... it's working locally and I've confirmed that `COMMIT_SHA` exists in the Docker image ...

Oh wait, does Heroku use the Docker image? I bet you it doesn't.

**Review by defong — APPROVED** [review]

**Review by vigneshmsft — APPROVED** [review]
LGTM

**Pull request merged**
