### PR TITLE
[1090] Added training details to be validated

### PR DESCRIPTION
**Pull request by defong**
:shipit:

### CODE REVIEW

**Comment by defong** [comment]
[User has created a trainee without a commencement date](https://trello.com/c/OE02Tw3r/1090-user-has-created-a-trainee-without-a-commencement-date)

**Review by AbigailMcP — COMMENTED** [review]
In the example data rake task:

```
  progress = {
    personal_details: true,
    contact_details: true,
    degrees: true,
    diversity: true,
    programme_details: true,
    training_details: true, # <- This needs to be added
  }
```

**Comment by defong** [comment]
heroku flushing for example rake

**Review by AbigailMcP — APPROVED** [review]

**Comment by defong** [comment]
https://github.com/DFE-Digital/register-trainee-teachers/pull/515#pullrequestreview-590378326

**Comment by ndgallon73** [comment]
Works for me!

**Pull request merged**
