### PR TITLE
[0221] Removed previous education

### PR DESCRIPTION
**Pull request by defong**
### Context
Previous education

### Changes proposed in this pull request
Removed previous education

### Guidance to review
There is no previous education

### CODE REVIEW

**Comment by defong** [comment]
[[L] Build "Add undergraduate degree" form](https://trello.com/c/3TgEm0wy/221-l-build-add-undergraduate-degree-form)

**Review by aliuk2012 — APPROVED** [review]
# Approving on this basis alone.... 😁👍 
image

**Review by SamJamCul — APPROVED** [review]
Looks good, does the commit need to have the `0` in `0221` though?

**Comment by defong** [comment]
> Looks good, does the commit need to have the `0` in `0221` though?

No idea force of habit after a thousand PR....

**Pull request merged**
