### PR TITLE
[5668] Nip a few N+1s

### PR DESCRIPTION
**Pull request by darokel**
### Context

https://trello.com/c/9KVtSd1G/5668-n1-query-systemadmindeadjobscontrollershow

Been trying to track down the N+1 reported by Sentry in the ticket above but hard to reproduce since it's in the Sidekiq dead set (which isn't backup/sanitised). Ended up finding/fixing a few others in the process.

### CODE REVIEW

**Comment by darokel** [comment]
[N+1 Query SystemAdmin::DeadJobsController#show](https://trello.com/c/9KVtSd1G/5668-n1-query-systemadmindeadjobscontrollershow)

**Review by defong — APPROVED** [review]
Looks fine to me :muscle:

**Review by carlosmartinez — APPROVED** [review]
Nice. Any thoughts on using [bullet](https://github.com/flyerhzm/bullet)?

**Comment by bj2k61** [comment]
[Deploy Azure resources for terraform](https://trello.com/c/mT2pqtU1/491-deploy-azure-resources-for-terraform)

**Comment by darokel** [comment]
> Nice. Any thoughts on using [bullet](https://github.com/flyerhzm/bullet)?

I've been using another one but will post in Slack and we can compare/decide between the two. Happy with either 👍

**Pull request merged**
