### PR TITLE
[3158] Add a TraineeStartStatusForm to capture commencement_status

### PR DESCRIPTION
**Pull request by archferns**
### Context
Add a new TraineeStartStatusForm, enabling a user to select one of 3 options
1. Trainee started ITT on time
2. Trainee started ITT after the course start date
3. Trainee did not start their ITT yet

### Changes proposed in this pull request
1. Add a new column called `commencement_status` against `trainees` to capture the value of this radio selection.
2. If the user selects the first option (itt started on time), use the course start date as trainee start date.
image

3. If the user selects the second option, show a date field to enable the user to input the trainee start date (much like existing flow)
image

4. a) If the user selects the last option (itt not yet started), unset the trainee start date.
image

    b) Ensure that the confirmation/updated views render the text "Trainee has not started yet"
    
image

### Guidance to review
1. On a non-draft trainee, In the "Trainee Progress" section, click the  "Change" link against the "Trainee start date" row.
2. **Manually change a bit in the URL** from trainee-start-date to trainee-start-status
  Eg if your URL is `blah-blah/trainee-start-date/edit`, change it to `blah-blah/trainee-start-status/edit`
3. Try choosing any of the three options, and attempt to update the trainee's start status/date.

### CODE REVIEW

**Comment by archferns** [comment]
image
@gregknight1 please could you review this text for me:
Select an option from the list
When the user has not selected any of the available radio options for ITT start date.

**Comment by archferns** [comment]
[Trainee start date form](https://trello.com/c/MT60YL0x/3158-trainee-start-date-form)

**Comment by gregknight1** [comment]
@archferns Should say:

**Select if the trainee started on time**

**Review by AbigailMcP — COMMENTED** [review]
Looks grand! Ready for product review.

I know we said to just keep the validation as is but:

Screenshot 2021-11-09 at 10 51 03

I'm wondering whether we should do the same as we do for course start date i.e. not more than one year from now? cc @ralph-hawkins

**Review by AbigailMcP — APPROVED** [review]
Code looks great!

Please could you double check the content for the confirmation page? At the moment it's looking like:

Screenshot 2021-11-09 at 14 21 17

But I think in the prototype it says "Confirm trainee start date", with the row labels "Trainee start date"

**Comment by archferns** [comment]
> 
> But I think in the prototype it says "Confirm trainee start date", with the row labels "Trainee start date"

Updated in https://github.com/DFE-Digital/register-trainee-teachers/pull/1719/commits/afb252d60dcf54d9e9838cddd7460584f6c6860d

I will card up https://github.com/DFE-Digital/register-trainee-teachers/pull/1719#pullrequestreview-801172115, since we want to avoid changing the existing form.

**Pull request merged**
