### PR TITLE
[2529] Fixed unrelated course issue

### PR DESCRIPTION
**Pull request by defong**
### Context
Fixed unrelated course issue
### Changes proposed in this pull request
Fixed unrelated course issue

Added data integrity to tests as there is relational integrity that neds to be retained
### Guidance to review
:shipit:

### CODE REVIEW

**Comment by defong** [comment]
[[L] Add magic link alternative signin method](https://trello.com/c/6PfxsZrL/2473-l-add-magic-link-alternative-signin-method)

**Comment by defong** [comment]
[Publish course issue with duplicate course codes](https://trello.com/c/BhzyJFSp/2529-publish-course-issue-with-duplicate-course-codes)

**Review by gpeng — CHANGES_REQUESTED** [review]
Could we add a test where there are two courses with the same code in the context that would have failed before this change?

**Comment by defong** [comment]
Closing this as this is a wider issue

**Pull request closed without merging**
