### PR TITLE
[7251] - Add POST /trainees/{trainee_id}/defer

### PR DESCRIPTION
**Pull request by Reyko**
### Context

[7251-endpoint-post-trainees-traineeid-defer](https://trello.com/c/JFS8sXzm/7251-endpoint-post-trainees-traineeid-defer)

### Changes proposed in this pull request

* Add endpoint to defer trainees
* Update docs for `v0.1`, `v1.0`

### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?
- [ ] Do we need to send any updates to DQT as part of the work in this PR?
- [ ] Does this PR need an ADR?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

### CODE REVIEW

**Review by kennyevil — APPROVED** [review]

**Review by tomtrentham — COMMENTED** [review]
I think the `defer_date` should be a required field, unless this has been confirmed by someone else as optional.

**Comment by Reyko** [comment]
> I think the `defer_date` should be a required field, unless this has been confirmed by someone else as optional.

Yeah that was one thing I was unsure about. Should the rest of the validations be triggered always? I followed [deferral_form.rb#L4](https://github.com/DFE-Digital/register-trainee-teachers/blob/7251-endpoint-post-trainees-traineeid-defer/app/forms/deferral_form.rb#L4)

**Comment by tomtrentham** [comment]
> > I think the `defer_date` should be a required field, unless this has been confirmed by someone else as optional.
> 
> Yeah that was one thing I was unsure about. Should the rest of the validations be triggered always? I followed [deferral_form.rb#L4](https://github.com/DFE-Digital/register-trainee-teachers/blob/7251-endpoint-post-trainees-traineeid-defer/app/forms/deferral_form.rb#L4)

@Reyko I think we can keep it simple here - check that `defer_date` is present, and is a date.

**Comment by Reyko** [comment]
> > > I think the `defer_date` should be a required field, unless this has been confirmed by someone else as optional.
> > 
> > 
> > Yeah that was one thing I was unsure about. Should the rest of the validations be triggered always? I followed [deferral_form.rb#L4](https://github.com/DFE-Digital/register-trainee-teachers/blob/7251-endpoint-post-trainees-traineeid-defer/app/forms/deferral_form.rb#L4)
> 
> @Reyko I think we can keep it simple here - check that `defer_date` is present, and is a date.

Refactored https://github.com/DFE-Digital/register-trainee-teachers/pull/4395/commits/b1ab53374ea23af3a1ece2125756499b1018866f

**Review by tomtrentham — APPROVED** [review]

**Pull request merged**
