### PR TITLE
[2507] & [2432] - A few niggles

### PR DESCRIPTION
**Pull request by darokel**
### Context

- https://trello.com/c/FkfxElIY/2507-form-pages-missing-error-summaries
- https://trello.com/c/aWpvIPuC/2432-if-you-leave-the-year-field-blank-when-it-errors-the-field-is-filled-with-0

### Changes proposed in this pull request

- Fixes a few issues outlined in the tickets above

### Guidance to review

Trainee ID & Start date forms

- View an existing non draft trainee, enter an invalid value for one of those forms and assert the error summary is shown (and the title reflects)

Dates

- Submit a personal details form for a non draft trainee with an empty year
- Assert the year field is still empty post validation

### CODE REVIEW

**Comment by darokel** [comment]
[Form pages missing error summaries](https://trello.com/c/FkfxElIY/2507-form-pages-missing-error-summaries)

**Comment by darokel** [comment]
[If you leave the year field blank, when it errors the field is filled with 0](https://trello.com/c/aWpvIPuC/2432-if-you-leave-the-year-field-blank-when-it-errors-the-field-is-filled-with-0)

**Review by AbigailMcP — APPROVED** [review]

**Comment by bbelward** [comment]
Trainee 

Screenshot 2021-08-18 at 18 00 14

**Comment by bbelward** [comment]
Trainee start date also working as expected. 

Screenshot 2021-08-18 at 18 00 33

**Comment by bbelward** [comment]
Year field also working as expected 
Screenshot 2021-08-18 at 18 03 15

**Comment by bbelward** [comment]
Nice work, all good from my side 👍

**Pull request merged**
