### PR TITLE
[7238, 7239] - Adds pen to deploy workflow

### PR DESCRIPTION
**Pull request by d-a-v-e**
* Adds pen testing ENV to the deploy workflow
* switches from OTP to DSI for sign-in

### CODE REVIEW

**Comment by d-a-v-e** [comment]
[New API ITHC Pre-requisites](https://trello.com/c/iAsBiA67/7238-new-api-ithc-pre-requisites)

**Review by tomtrentham — APPROVED** [review]
LGTM :shipit:

**Review by RMcVelia — APPROVED** [review]

**Comment by RMcVelia** [comment]
probably need to add pen here too https://github.com/DFE-Digital/register-trainee-teachers/blob/main/.github/actions/deploy/action.yml#L128

**Comment by d-a-v-e** [comment]
[PEN Test env: Enable DSI](https://trello.com/c/sf3JghZR/7239-pen-test-env-enable-dsi)

**Pull request merged**
