### PR TITLE
[7607] - Normalise emails before saving

### PR DESCRIPTION
**Pull request by kennyevil**
### Context

https://trello.com/c/AEuMWFoC/7607-normalise-email-addresses-before-saving

### Changes proposed in this pull request

Downcase email addresses as well as removing whitespace before saving.

### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?
- [ ] Do we need to send any updates to DQT as part of the work in this PR?
- [ ] Does this PR need an ADR?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

### CODE REVIEW

**Review by defong — COMMENTED** [review]
Do we need a migration to have all the existing email to be down-cased?

**Comment by kennyevil** [comment]
> Do we need a migration to have all the existing email to be down-cased?

I was thinking it might be something that could be accomplished via the console. I'll get a count to see how many would have to be changed.

**Comment by kennyevil** [comment]
There are 45 User accounts with non-unique email addresses and 1190 Trainee records with non-unique email addresses. I've filtered out all of the records with `discarded_at` set to anything other than nil. I think identifying and cleaning up the data is a task in itself. @tomtrentham what do you think?

**Comment by tomtrentham** [comment]
> There are 45 User accounts with non-unique email addresses and 1190 Trainee records with non-unique email addresses. I've filtered out all of the records with `discarded_at` set to anything other than nil. I think identifying and cleaning up the data is a task in itself. @tomtrentham what do you think?

@kennyevil Yes, this sounds like a task in itself. I think it can be legitimate to have more than one Trainee record with the same email address, but for Users we should do more investigation.

**Comment by kennyevil** [comment]
@tomtrentham As discussed, I believe this will be safe to merge now and we can clean up the duplicate accounts independently. The risk is that users might not be able to update their email addresses if there's another account with an identical email address, but it should stop further accounts with duplicate email addresses being created.

**Review by tomtrentham — APPROVED** [review]

**Pull request merged**
