### PR TITLE
[3501] Autocomplete undefined bug fix

### PR DESCRIPTION
**Pull request by mooktakim**
### Context

https://trello.com/c/m0DlB1CT/3501-m-degree-type-autocomplete-bug

### Changes proposed in this pull request

* I don't know how, but it works

### Guidance to review

* Set course name one (or some other autocomplete field) to non-listed value
* Does it show "undefined" when you first click the textbox?

### Important business

* Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
* Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

### CODE REVIEW

**Comment by mooktakim** [comment]
[[M] Degree type autocomplete bug](https://trello.com/c/m0DlB1CT/3501-m-degree-type-autocomplete-bug)

**Comment by edwardhorsford** [comment]
I'm not sure this is the right way to solve this - you can get `undefined` as a result of non errors - any page preloading an option could have it.

I think the issue is caused by passing an object to `defaultValue` - and the autocomplete has a bug with `defaultValue` where it tries to render the object. We should be able to adapt what we send to `defaultValue` - or possibly consider moving away from `.enhanceSelectElement()`

**Comment by edwardhorsford** [comment]
Some related issues:
https://github.com/alphagov/accessible-autocomplete/issues/495
https://github.com/alphagov/accessible-autocomplete/issues/424

**Review by edwardhorsford — APPROVED** [review]
On playing with this I think this is probably making the best of a bad situation due to https://github.com/alphagov/accessible-autocomplete/issues/495

It's not really semantically correct for the suggestion function to do this, but the result is clearer for users - and whilst the autocomplete has this bug open, it's better than nothing.

Note we'd probably need to do a different solution when we start accepting free text in this - as I think this solution would not be correct when doing that or when not using the `enhanceSelectElement()` mode.

**Review by AbigailMcP — APPROVED** [review]

**Pull request merged**
