### PR TITLE
[xxx] Add banner for removal of dashboard numbers

### PR DESCRIPTION
**Pull request by darokel**
### Context

Screenshot 2023-10-12 at 12 06 09

### CODE REVIEW

**Review by carlosmartinez — APPROVED** [review]
i like it!

**Comment by carlosmartinez** [comment]
although, ironically, your screenshot includes dashboard numbers

**Comment by darokel** [comment]
> although, ironically, your screenshot includes dashboard numbers

rebased and replaced :)

**Comment by darokel** [comment]
Closing as this is now redundant

**Pull request closed without merging**
