### PR TITLE
[1574] Anonymise usernames for system admins in the timeline

### PR DESCRIPTION
**Pull request by AbigailMcP**
### Context

https://trello.com/c/l9SrTiPZ/1574-s-anonymise-admin-names-from-the-timeline

### Changes proposed in this pull request

Before: If a system admin (like a dev) made a change to a trainee on behalf of a user, their full name would be visible on the timeline.

Now: We just show 'Administrator' rather than the dev's name. Names of other users are still visible.

Screenshot 2021-04-26 at 13 04 24

### Guidance to review

- Log in as the system admin 'Adam Baker'
- Choose a non-draft trainee
- Make a change to the trainee e.g. change their name
- Visit the timeline
- See that "Administrator" is visible rather than "Adam Baker" for the related timeline entry

### CODE REVIEW

**Comment by AbigailMcP** [comment]
[[S] Anonymise admin names from the timeline](https://trello.com/c/l9SrTiPZ/1574-s-anonymise-admin-names-from-the-timeline)

**Review by defong — APPROVED** [review]

**Comment by gregknight1** [comment]
Look fine from a content perspective @AbigailMcP

**Comment by GeoffJohnson** [comment]
I'm getting a nationality error :-( 
Screenshot 2021-04-28 at 10 11 29

**Comment by edwardhorsford** [comment]
I wonder if this should be `DFE administrator` - @gregknight1 what do you think?

**Comment by AbigailMcP** [comment]
> I'm getting a nationality error :-(

Rebasing to master - I think this is an unrelated bug that's been fixed elsewhere.

**Comment by AbigailMcP** [comment]
> I wonder if this should be `DFE administrator` - @gregknight1 what do you think?

Yeah I was wondering this - in case they also call _themselves_ administrators?

**Comment by GeoffJohnson** [comment]
All good now :-)

**Comment by gregknight1** [comment]
> > I wonder if this should be `DFE administrator` - @gregknight1 what do you think?
> 
> Yeah I was wondering this - in case provider users also call _themselves_ administrators?

Yeah, think that's a sensible thing to do in this case.

**Pull request merged**
