### PR TITLE
Add Rake Task for Removing Duplicates

### PR DESCRIPTION
**Pull request by AdColvin**
### Context
[Trello](https://trello.com/c/t2CA84f2)

Staffordshire University have sent over a spreadsheet of around 70 trainees who have duplicate records in Register. The duplicates need to be deleted.

### Changes proposed in this pull request
Added a rake task to search for the duplicates based on the trainee's email address and discard the duplicates.  

### Usage
For a CSV file in the following format: 

```csv
trainee_id,email
123,duplicate@example.com
456,duplicate@example.com
789,duplicate@example.com
890,unique@example.com
```

The rake task can be called like this: 
` bundle exec rake trainee:remove_duplicates [path_to_csv]`

### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?
- [ ] Do we need to send any updates to DQT as part of the work in this PR?
- [ ] Does this PR need an ADR?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

### CODE REVIEW

**Review by tomtrentham — COMMENTED** [review]
Be great if we could have some simple docs to describe how to use this with an example of the CSV format.

**Review by tomtrentham — COMMENTED** [review]
Thanks for putting some instructions in the PR description. I think it would be useful to have these in the app docs as well, so they're easy to find for future use.
I reckon a section in `docs/support_playbook.md` would be good as this could be a regular task which falls to support.

**Comment by AdColvin** [comment]
> Thanks for putting some instructions in the PR description. I think it would be useful to have these in the app docs as well, so they're easy to find for future use. I reckon a section in `docs/support_playbook.md` would be good as this could be a regular task which falls to support.

Ah sorry, I thought this would be a run-once thing, but then I remember you saying this could stick around. I'll update 👍

**Comment by AdColvin** [comment]
Updated [here](https://github.com/DFE-Digital/register-trainee-teachers/pull/4409/commits/d5a2254a3a08b89260cb7c0fbab0ee80fb3d394d) @tomtrentham

**Review by tomtrentham — APPROVED** [review]
Great docs, thank you. 🚀

**Comment by AdColvin** [comment]
[Duplicate records - Staffordshire University](https://trello.com/c/t2CA84f2/7293-duplicate-records-staffordshire-university)

**Pull request merged**
