### PR TITLE
[5316] Bulk recommend -  dynamic QTS or EYTS

### PR DESCRIPTION
**Pull request by AbigailMcP**
### Context

https://trello.com/c/eRBHiwlB/5316-s-dynamically-say-whether-the-user-is-recommending-trainees-for-qts-or-eyts

### Changes proposed in this pull request

- Add helper that takes a collection of rows and returns QTS if all QTS
  EYTS if all EYTS, QTS or EYTS if mixture
- Add model methods `qts?` and `eyts` to recommendations_upload_row
  that returns true if the associated trainee is working towards QTS/EYTS respectively
- Use helper in views (screenshots below)

Also:
- Remove scope which wasn't being used anywhere

### Guidance to review

Summary page bullets:

Screenshot 2023-03-22 at 09 43 08

Summary page all errors:

Screenshot 2023-03-21 at 12 26 02

Fix errors page:

Screenshot 2023-03-21 at 12 20 25

Check page:

Screenshot 2023-03-22 at 11 18 41

Confirmation page:

Screenshot 2023-03-21 at 13 11 34

### Important business

- [ ] ~Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?~
- [ ] ~Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?~
- [ ] ~Do we need to send any updates to DQT as part of the work in this PR?~
- [ ] ~Does this PR need an ADR?~

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

### CODE REVIEW

**Review by richardpattinson — APPROVED** [review]
Looks good to me!

**Comment by claire-hughez** [comment]
image
@johndoates the content here feels a bit weird to me. 'You need to review the errors before you can recommend for QTS', but then we talk about recommending a trainee for EYTS on the last line. Should this be changed to 'QTS or EYTS'? Feels quite complex.

**Comment by claire-hughez** [comment]
image
Is this missing a full stop @johndoates

**Comment by johndoates** [comment]
> image Is this missing a full stop @johndoates

Yes. There should be a full stop after "their details".

**Comment by AbigailMcP** [comment]
@johndoates following our discussions, updated summary page:

Screenshot 2023-03-27 at 11 20 21

**Pull request merged**
