### PR TITLE
[2731] Bug - updated trainee details don't show on timeline

### PR DESCRIPTION
**Pull request by AbigailMcP**
### Context

https://trello.com/c/7mFjLtRy/2731-bug-updating-trainee-details-often-doesnt-show-on-timeline

### Changes proposed in this pull request

Includes more trainee fields in the timeline.
Also fixes a bug whereby fields that were intentionally left blank by the user in a form would be reported as changed.

### Guidance to review
Change some things on a non-draft trainee and check they appears on the timeline. Especially:
- course related fields
- funding related fields

### CODE REVIEW

**Comment by AbigailMcP** [comment]
[Bug - updating trainee details often doesn't show on timeline](https://trello.com/c/7mFjLtRy/2731-bug-updating-trainee-details-often-doesnt-show-on-timeline)

**Review by archferns — APPROVED** [review]

**Comment by bbelward** [comment]
I'm getting duplicate entries on the timeline for age range, even though I only made one change (trainee is pending TRN and on the AO route), but not for subject 
1446-duplicate-age-range

**Comment by bbelward** [comment]
Not sure if this is entirely related, but noticed the PGTA trainees error most of the time, but not all the time. 
1446-PGTAcrashing

**Comment by bbelward** [comment]
3. More weird behaviour, sometimes funding duplicates when you make an edit, and sometimes it doesn't. 
What I did: 
change course from maths to biology > change age range > change bursary > saw duplicate funding entry, but not age range 
on the same trainee (this bit is in the GIF) 
change course from biology to physics > change age range > change bursary > saw duplicate age range, but single bursary update in the timeline. 
1446-fundingduplicates

**Comment by AbigailMcP** [comment]
> Not sure if this is entirely related, but noticed the PGTA trainees error most of the time, but not all the time.
> 1446-PGTAcrashing

Unrelated but annoying - I'll card up separately. It's to do with our auto-generated example data.

**Comment by AbigailMcP** [comment]
> I'm getting duplicate entries on the timeline for age range, even though I only made one change (trainee is pending TRN and on the AO route), but not for subject

This should be fixed now.

**Comment by AbigailMcP** [comment]
> 1. More weird behaviour, sometimes funding duplicates when you make an edit, and sometimes it doesn't.
>    What I did:
>    change course from maths to biology > change age range > change bursary > saw duplicate funding entry, but not age range
>    on the same trainee (this bit is in the GIF)
>    change course from biology to physics > change age range > change bursary > saw duplicate age range, but single bursary update in the timeline.

This was difficult to replicate, but I think also to do with our auto-generated data. I've made a tweak which could fix this.

**Comment by bbelward** [comment]
1. when I select primary (on trainee on EY assessment only route), it errors asking me to enter a subject, despite there being no option to do so on the pag
educationphase-PRs
e

**Comment by bbelward** [comment]
Changed the funding details on a trainee on AO and still got duplicate updates on the timeline. Was working as expected for course details. 

Given it could be the autogenerated data, I'd say let's just merge!

**Pull request merged**
