### PR TITLE
[5782] Amended so that the csv is downloaded as a stream

### PR DESCRIPTION
**Pull request by defong**
### Context
Return csv as a stream

### Changes proposed in this pull request
Amended to return csv as a stream
The end points `performance_profiles` &`itt_new_starter_data_sign_off` now support streaming.

### Guidance to review

Log in as a persona and head to https://register-pr-3495.test.teacherservices.cloud/reports/performance-profiles, the available persona are from the sanitised backup which will reflect a closer real life experience. Click on the `Export` button should trigger the download without any delay.

All the current one does the calculation and generation before the file can be saved.

### Important business

- [x] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [x] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?
- [x] Do we need to send any updates to DQT as part of the work in this PR?
- [x] Does this PR need an ADR?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

### CODE REVIEW

**Comment by defong** [comment]
[Spike: Test exporting large number of trainees on Report page](https://trello.com/c/xlzSIlfP/5782-spike-test-exporting-large-number-of-trainees-on-report-page)

**Comment by darokel** [comment]
Looks good, I've tested this out locally and it's defo the best way to go forward (vs scenic alternative). The file download is kicked off asynchronously by the browser so the user isn't waiting for the app to respond.

**Comment by defong** [comment]
[Stream large number of trainees on Report page](https://trello.com/c/0JLK0fXB/5943-stream-large-number-of-trainees-on-report-page)

**Review by darokel — APPROVED** [review]
image

**Review by carlosmartinez — APPROVED** [review]

**Pull request merged**
