### PR TITLE
[881] Fixed dead persona

### PR DESCRIPTION
**Pull request by defong**
### Context
Dead persona
### Changes proposed in this pull request
Easter is still sometime away, performing dark magic instead

### Guidance to review

https://rtt-review-pr-402.herokuapp.com/personas
 

It broke all the other review apps

image

### CODE REVIEW

**Comment by jesseyuen** [comment]
Let's not divert too far from the current pattern. I'd suggest this:

Screenshot 2021-01-18 at 13 24 35

**Review by gpeng — APPROVED** [review]

**Comment by gpeng** [comment]
> Let's not divert too far from the current pattern. I'd suggest this, although it still tells us nothing about what a sys admins access means.
> 
> EDIT: Updating this to remove the word 'system'
> 
> Screenshot 2021-01-18 at 13 50 07

@jesseyuen - @edwardhorsford  was quite keen the avoid `adminstrator` for this role as it might clash with something we want to use in the future for users. Probably not 'a biggy' here though.

**Comment by defong** [comment]
image

**Comment by defong** [comment]
image

**Comment by defong** [comment]
[Persona is broken](https://trello.com/c/K0t7FOz9/881-persona-is-broken)

**Comment by jesseyuen** [comment]
> > Let's not divert too far from the current pattern. I'd suggest this, although it still tells us nothing about what a sys admins access means.
> > EDIT: Updating this to remove the word 'system'
> > Screenshot 2021-01-18 at 13 50 07
> 
> @jesseyuen - @edwardhorsford was quite keen the avoid `adminstrator` for this role as it might clash with something we want to use in the future for users. Probably not 'a biggy' here though.

Agreed, it's a bit ambiguous. Let's review roles/names etc sometime soon?

**Pull request merged**
