### PR TITLE
Make `7-14` and `5-14` age ranges available to _secondary_ level

### PR DESCRIPTION
**Pull request by stevehook**
### Context
This work was triggered by a support request in which a provider questioned why the `7-14` age range was available for _Primary_ courses. (It already was for _Secondary_). This made Register inconsistent with Publish. 

### Changes proposed in this pull request
This PR just adds the _Primary_ level for the `7-14` and `5-14` age ranges.

Longer term we want to consider making the `dfe-reference-data` gem the single source of truth across all services.

### Guidance to review
- What could be the unintended knock-on effects of this?

### Important business

- [x] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [x] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?
- [x] Do we need to send any updates to DQT as part of the work in this PR?
- [x] Does this PR need an ADR?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

### CODE REVIEW

**Review by carlosmartinez — APPROVED** [review]
1. fine
2. why do we define age ranges in so many places?
3. when can we get rid of DTTP codesets?

**Comment by stevehook** [comment]
> * fine
> * why do we define age ranges in so many places?
> * when can we get rid of DTTP codesets?

It looks like there are at least three lists of age ranges in the codebase. 

- `::AgeRange` just declares the list of allowed age range values. The values themselves are arrays because we store age ranges in two attributes, an upper and lower bound rather than as say a string constant.
- `Dttp::CodeSets::AgeRanges` was I guess originally meant for mapping import values from DTTP to Register values as declared in `::AgeRange`. But it's also used to fetch the list of permitted values that populate radio button lists or dropdown.
- `Hesa::CodeSets::AgeRanges` is only used to map HESA values to Register values as (declared in `::AgeRange`). It doesn't seem to include the full list because I guess not all are used by HESA.

We could rename the `Dttp::CodeSets::AgeRanges` to something less confusing if it's not longer needed for DTTP import and possible merge it with `::AgeRange`. I think we need to keep `Hesa::CodeSets::AgeRanges` for now.

**Comment by carlosmartinez** [comment]
> > * fine
> > * why do we define age ranges in so many places?
> > * when can we get rid of DTTP codesets?
> 
> It looks like there are at least three lists of age ranges in the codebase.
> 
> * `::AgeRange` just declares the list of allowed age range values. The values themselves are arrays because we store age ranges in two attributes, an upper and lower bound rather than as say a string constant.
> * `Dttp::CodeSets::AgeRanges` was I guess originally meant for mapping import values from DTTP to Register values as declared in `::AgeRange`. But it's also used to fetch the list of permitted values that populate radio button lists or dropdown, given a course level (Primary or Secondary).
> * `Hesa::CodeSets::AgeRanges` is only used to map HESA values to Register values as (declared in `::AgeRange`). It doesn't seem to include the full list because I guess not all are used by HESA.
> 
> We could rename the `Dttp::CodeSets::AgeRanges` to something less confusing if it's not longer needed for DTTP import and possible merge it with `::AgeRange`. I think we need to keep `Hesa::CodeSets::AgeRanges` for now.

Thanks for that, Steve.

I think it's a good idea to merge the DTTP AgeRanges into `::AgeRange` (and the initializer is probably a reasonable place for it).

Any of this that could/should go in dfe-reference-data?

**Comment by stevehook** [comment]
> > > * fine
> > > * why do we define age ranges in so many places?
> > > * when can we get rid of DTTP codesets?
> > 
> > 
> > It looks like there are at least three lists of age ranges in the codebase.
> > 
> > * `::AgeRange` just declares the list of allowed age range values. The values themselves are arrays because we store age ranges in two attributes, an upper and lower bound rather than as say a string constant.
> > * `Dttp::CodeSets::AgeRanges` was I guess originally meant for mapping import values from DTTP to Register values as declared in `::AgeRange`. But it's also used to fetch the list of permitted values that populate radio button lists or dropdown, given a course level (Primary or Secondary).
> > * `Hesa::CodeSets::AgeRanges` is only used to map HESA values to Register values as (declared in `::AgeRange`). It doesn't seem to include the full list because I guess not all are used by HESA.
> > 
> > We could rename the `Dttp::CodeSets::AgeRanges` to something less confusing if it's not longer needed for DTTP import and possible merge it with `::AgeRange`. I think we need to keep `Hesa::CodeSets::AgeRanges` for now.
> 
> Thanks for that, Steve.
> 
> I think it's a good idea to merge the DTTP AgeRanges into `::AgeRange` (and the initializer is probably a reasonable place for it).
> 
> Any of this that could/should go in dfe-reference-data?

I've refactored this a bit to merge `Dttp::CodeSets::AgeRanges` and `::AgeRange`. To answer the question about `dfe-reference-data` I think it's a yes. Most of this stuff could go in there. I'm not sure about the HESA mappings but even that seems as though it should be universal.

**Comment by andrewscrivener** [comment]
I've tested and verified that the new age values are available for Primary courses. :shipit:

**Pull request merged**
