### PR TITLE
[7771] - lock rubyzip until 3.0 release

### PR DESCRIPTION
**Pull request by d-a-v-e**
### Context

[Update/review really old gem rubyzip](https://trello.com/c/O9Oy6Asv/7771-update-review-really-old-gem-rubyzip)

### Changes proposed in this pull request

locks to 2.3.x, (migration to 3.0.0 when rubyzip is out of alpha)

### CODE REVIEW

**Review by defong — COMMENTED** [review]
Not sure about locking it down, I see locking it down means we will forget, and before we know it had snowballed.

Perhaps we should just allow it to break when gem is released and fix it then. 

deferring to @tomtrentham 

Out of interest where does this zip thing getting used?

**Comment by d-a-v-e** [comment]
> Not sure about locking it down, I see locking it down means we will forget, and before we know it had snowballed.
> 
> Perhaps we should just allow it to break when gem is released and fix it then.
> 
> deferring to @tomtrentham
> 
> Out of interest where does this zip thing getting used?

its got _super_ small use case. Basically in a fallback situation where we manually upload the HESA xml file, if we upload it as zipped, then the `app/services/hesa/sync_students.rb` will need to unzip it. Basically its never used.

**Comment by d-a-v-e** [comment]
@defong  so just wait for dependabot to attempt an upgrade? I'm good with that

**Review by defong — APPROVED** [review]
Oh right so either case gem is going to be dead code and we can delete?

The path of least resistance

**Pull request closed without merging**
