### PR TITLE
[5782] Spike test exporting large number of trainees on report page via scenic

### PR DESCRIPTION
**Pull request by defong**
### Context

Scenic

### Changes proposed in this pull request
The amount of data, required to generate the csv report will tombstone the server.
By using scenic and leverage materialised views on postgres, this should cut down the amount of network traffic for the postgres database server

### Guidance to review
This is just a rough cut.
Considerations
- Are we comfortable with sql?
- Tuning sql
- Move more calculation to postgres vs ruby land
- Remove need to do additional joins from ruy land
- Is it really necessary 80 columns of data?

#### Basic benchmark
```ruby
Benchmark.bm do |x|
  trainees = Trainee.all
  x.report('new trainees report') do 
    TraineeReport.includes.where(id: trainees.ids).map(&:to_csv) 
  end

  x.report('new trainees report with includes') do 
    TraineeReport.includes({ course_allocation_subject: [:subject_specialisms] },                          :end_academic_cycle, :start_academic_cycle)
      .where(id: trainees.ids).map(&:to_csv) 
  end

  x.report('old trainees report') do 
    trainees.each do |trainee|
      trainee_report = Reports::TraineeReport.new(trainee)
      Reports::TraineesReport.headers.map { |value| CsvValueSanitiser.new(trainee_report.send(value)).sanitise }
    end
  end

  x.report('old trainees report with includes') do 
    trainees.includes(:apply_application, { course_allocation_subject: [:subject_specialisms] }, :degrees,  :disabilities, :employing_school, :end_academic_cycle, :lead_school, { nationalisations: :nationality }, :nationalities, :provider, :start_academic_cycle, :trainee_disabilities, { placements: :school }, :hesa_students, :withdrawal_reasons).each do |trainee|
      trainee_report = Reports::TraineeReport.new(trainee)
      Reports::TraineesReport.headers.map { |value| CsvValueSanitiser.new(trainee_report.send(value)).sanitise }   
    end
  end
end
```

Results
```
                                  user        system     total       real
new trainees report               1462.578482  40.224168 1502.802650 (1628.204698)
new trainees report with includes  738.661043  16.748677  755.409720 (825.567644)
old trainees report               4448.564857 117.660404 4566.225261 (4909.008117)
old trainees report with includes  877.178613  16.840686  894.019299 (966.026140)

Approx 
134976 / 1628 =  82 trainees per sec
134976 /  825 = 163 trainees per sec
134976 / 4909 =  27 trainees per sec
134976 /  966 = 139 trainees per sec
```
### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?
- [ ] Do we need to send any updates to DQT as part of the work in this PR?
- [ ] Does this PR need an ADR?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

### CODE REVIEW

**Comment by defong** [comment]
[Spike: Test exporting large number of trainees on Report page](https://trello.com/c/xlzSIlfP/5782-spike-test-exporting-large-number-of-trainees-on-report-page)

**Review by stevehook — COMMENTED** [review]
This looks very good but do the benchmarks indicate that the performance gain is fairly small when the `includes` are 'included'?

I guess we'd need an overnight job to refresh the view? The biggest concern with this approach is maintainability (the same as with any change that adds non-trivial SQL queries in our codebase).

**Comment by defong** [comment]
> This looks very good but do the benchmarks indicate that the performance gain is fairly small when the `includes` are 'included'?

```
                                  user        system     total       real
new trainees report with includes  738.661043  16.748677  755.409720 (825.567644)
old trainees report with includes  877.178613  16.840686  894.019299 (966.026140)

Approx 
134976 /  825 = 163 trainees per sec
134976 /  966 = 139 trainees per sec
```

```
100 / 139 * 163 = 117
```

So the gain is about 17% difference

> I guess we'd need an overnight job to refresh the view? The biggest concern with this approach is maintainability (the same as with any change that adds non-trivial SQL queries in our codebase).

Yeah that is also something that we will need to consider for the future us.

**Comment by defong** [comment]
Verdict
Until we really really need this and we have no better options

Why
It will become a future issue in terms of maintenance.

Options
Don't use production database to do reporting

**Pull request closed without merging**
