### PR TITLE
[3311] Enable draft records page

### PR DESCRIPTION
**Pull request by darokel**
### Context

- https://trello.com/c/wcIowvJW/3311-s-enable-draft-record-page

### Changes proposed in this pull request

- Render the drafts page in the main nav bar
- Update links on the homepage 
- Remove draft sets from registered trainees results
- Fix tests

### Guidance to review

Have a play with the review app

### CODE REVIEW

**Comment by richardpattinson** [comment]
[Dev: include a generic sciences option in the subject filters](https://trello.com/c/IWTnQu0R/3288-dev-include-a-generic-sciences-option-in-the-subject-filters)

**Comment by darokel** [comment]
[[S] Enable Draft record page](https://trello.com/c/wcIowvJW/3311-s-enable-draft-record-page)

**Review by edwardhorsford — CHANGES_REQUESTED** [review]
A few snags:

1. Page title of drafts page should be `Draft records...`
2. The link on the homepage `View all registered trainees (360)` can just link to the registered trainees tab without any filters applied (no longer need to exclude drafts)
3. From the draft pages (overview and check record) the back links should say `All drafts`
4. From draft confirm pages the links back to the draft should say `Back to draft record` (this might be a preexisting bug)
5. When creating a new trainee there is no caption `Draft` above the heading on the question `What typeof training are they doing?` (it later appears if you go back to this page)
6. The second tab should be `Registered trainees` not `Trainee records` - affects page h1, page title, tab name

**Review by edwardhorsford — APPROVED** [review]

**Comment by gpeng** [comment]
Rebased from main and added service update:
Screenshot 2022-01-04 at 12 11 36

**Pull request merged**
