### PR TITLE
[975] Fix asset path for fallback crown image

### PR DESCRIPTION
**Pull request by AbigailMcP**
### Context

https://trello.com/c/PhYeThFO/975-the-fallback-image-for-the-crown-logo-contains-ruby-in-the-markup

### Changes proposed in this pull request

Evaluate ruby code before passing in as fallback image source.

### Guidance to review

Check the page source and see that the correct image path is being supplied to the `<image>` tag.

### CODE REVIEW

**Comment by AbigailMcP** [comment]
[The fallback image for the crown logo contains Ruby in the markup](https://trello.com/c/PhYeThFO/975-the-fallback-image-for-the-crown-logo-contains-ruby-in-the-markup)

**Review by dankmitchell — APPROVED** [review]

**Comment by AbigailMcP** [comment]
@gpeng - I've fixed the ruby code, but where should this image actually be 'living'?

**Comment by dankmitchell** [comment]
@AbigailMcP the image is part of the govuk-frontend package.

**Comment by edwardhorsford** [comment]
Nice! One less bug for @defong and I to raise 😉

**Pull request merged**
