### PR TITLE
Remove sandbox env configuration

### PR DESCRIPTION
**Pull request by RMcVelia**
### Context

Remove sandbox configuration files 

https://trello.com/c/AqsJobyi/4343-remove-register-sandbox

### Changes proposed in this pull request

Remove sandbox from Makefile
Remove config files

### Guidance to review

confirm sandbox removed

### Important business

- [ ] Does this PR introduce any PII fields that need to be overwritten or deleted in db/scripts/sanitise.sql?
- [ ] Does this PR change the database schema? If so, have you updated the config/analytics.yml file and considered whether you need to send 'import_entity' events?

NB: Please notify the #twd_data_insights team and ask for a review if new fields are being added to analytics.yml

### CODE REVIEW

**Comment by saliceti** [comment]
Can we remove the config/sandbox.rb file as well?

**Comment by saliceti** [comment]
There are mentions to sandbox in rails.yml, webpacker.yml, style.scss, Readme

**Review by markhallen — APPROVED** [review]

**Comment by RMcVelia** [comment]
> There are mentions to sandbox in rails.yml, webpacker.yml, style.scss, Readme

removed all except Readme, as this is referring to apply

**Comment by RMcVelia** [comment]
> Can we remove the config/sandbox.rb file as well?

Removed config/environments/sandbox.rb

**Review by saliceti — APPROVED** [review]

**Pull request merged**
